kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
  - containerPort: 30081
    hostPort: 30081
  - containerPort: 9090
    hostPort: 9090
  - containerPort: 3100
    hostPort: 3100
  - containerPort: 3000
    hostPort: 3000
