apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
      - name: grpc
        image: grpc-server:latest
        imagePullPolicy: Never  # Important: uses your locally built image
        ports:
        - containerPort: 50051
        - containerPort: 2112
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 10