apiVersion: v1
kind: Service
metadata:
  name: grpc-gateway
  namespace: app-ns
spec:
  selector:
    app: grpc-gateway
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    nodePort: 30081   # Access via <NodeIP>:30081