apiVersion: v1
kind: Service
metadata:
  name: grpc
  namespace: app-ns
spec:
  selector:
    app: grpc
  type: NodePort
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    nodePort: 30051   # Access via <NodeIP>:30051
  - name: metrics
    port: 2112
    targetPort: 2112
    nodePort: 32112   # Optional: direct access to metrics