apiVersion: v1
kind: Service
metadata:
  name: jrpc
  namespace: app-ns
spec:
  selector:
    app: jrpc
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080   # Access via <NodeIP>:30080